#!/usr/bin/env bash

flatpak install flathub com.github.tchx84.Flatseal -y

flatpak install flathub net.nokyan.Resources -y

flatpak install flathub com.spotify.Client -y

flatpak install flathub page.codeberg.libre_menu_editor.LibreMenuEditor -y

flatpak install flathub io.podman_desktop.PodmanDesktop -y

flatpak install flathub io.github.dvlv.boxbuddyrs -y

flatpak install flathub org.telegram.desktop -y

flatpak install flathub app.zen_browser.zen -y

flatpak install flathub org.chromium.Chromium -y

flatpak install flathub com.abisource.AbiWord -y

flatpak install flathub com.github.phase1geo.minder -y
